RecipeFormatVersion: "2020-01-25"
ComponentName: "com.labs.CPUFilter"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "Greengrass Core component that filters CPU metrics from IoT devices."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentConfiguration:
  DefaultConfiguration:
    Period: 0.5
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        com.labs.CpuFilter:pubsub:1:
          policyDescription: Publish and subscribe to any topic
          operations:
            - aws.greengrass#SubscribeToIoTCore
            - aws.greengrass#SubscribeToTopic
            - aws.greengrass#PublishToTopic
            - aws.greengrass#PublishToIoTCore
          resources:
            - "*"
      aws.greengrass.ipc.pubsub:
        com.labs.CpuFilter:iotcore:1:
          policyDescription: "Allow publishing to IoT Core"
          operations:
            - "aws.greengrass#PublishToIoTCore"
            - aws.greengrass#SubscribeToIoTCore
            - aws.greengrass#SubscribeToTopic
            - aws.greengrass#PublishToTopic
          resources:
            - "*"
Manifests:
  - Platform:
      os: all
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/greengrass-cpu-filter.zip"
        Unarchive: ZIP
    Lifecycle:
      Install:
        Script: |
          python3 -m pip install virtualenv
          python3 -m virtualenv .venv
          . .venv/bin/activate
          python3 -m pip install -r {artifacts:decompressedPath}/greengrass-cpu-filter/requirements.txt
        RequiresPrivilege: true
      Run:
        Script: |
          . .venv/bin/activate
          python3 {artifacts:decompressedPath}/greengrass-cpu-filter/src/main.py
